/**
 * Closed error code enum for the Gateway Core.
 * Adding a new code requires editing this file + spec amendment.
 * No magic strings allowed outside this enum.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INSUFFICIENT_TRUST = 'INSUFFICIENT_TRUST',
  INSUFFICIENT_TOKENS = 'INSUFFICIENT_TOKENS',
  TENANT_NOT_RESOLVED = 'TENANT_NOT_RESOLVED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  HMAC_INVALID = 'HMAC_INVALID',
  KEY_REVOKED = 'KEY_REVOKED',
  WORKFLOW_VIOLATION = 'WORKFLOW_VIOLATION',
}

/** HTTP status mapping for each error code. */
export const ERROR_CODE_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.UNPROCESSABLE_ENTITY]: 422,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.BAD_GATEWAY]: 502,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.INSUFFICIENT_TRUST]: 403,
  [ErrorCode.INSUFFICIENT_TOKENS]: 402,
  [ErrorCode.TENANT_NOT_RESOLVED]: 400,
  [ErrorCode.IDEMPOTENCY_KEY_REUSED]: 409,
  [ErrorCode.HMAC_INVALID]: 401,
  [ErrorCode.KEY_REVOKED]: 401,
  [ErrorCode.WORKFLOW_VIOLATION]: 422,
};
